version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app/
    links:
      - database
    depends_on:
      - database
  database:
    image: mysql:8.0.34
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
