default: &default
  adapter: mysql2
  username: "<%= ENV['DB_USERNAME'] || 'root' %>"
  password: "<%= ENV['DB_PASSWORD'] || 'root' %>"
  host:     "<%= ENV['DB_HOSTNAME'] || 'database' %>"
  port:     "<%= ENV['DB_PORT'] || '3306' %>"

development:
  <<: *default
  database: todos_development

test:
  <<: *default
  database: todos_test

production:
  <<: *default
  database: todos_production
