default: &default
  adapter: mysql2
  # username: "<%= ENV['DB_USERNAME'] %>"
  # password: "<%= ENV['DB_PASSWORD'] %>"
  # host:     "<%= ENV['DB_HOSTNAME'] %>"
  # port:     "<%= ENV['DB_PORT'] %>"

  username: root
  password: root
  host:     database                #Must match database container name
  port:     3306

development:
  <<: *default
  database: todos_development

test:
  <<: *default
  database: todos_test

production:
  <<: *default
  database: todos_production
