default: &default
  adapter: mysql2
  username: todos_admin
  password: strong_password
  host: localhost

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: todos_development

test:
  <<: *default
  database: todos_test

production:
  <<: *default
  database: todos_production
