apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo #Pods app name (kubectl get pods -l app=todo)
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: omardiaa/todos-rails-app:1.2
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"   # Maximum memory allowed in Mebibytes
              cpu: "500m"       # Maximum CPU allowed (500 milliCPU or 0.5 CPU Core)
            requests:
              memory: "128Mi"   # Initial memory request in Mebibytes
              cpu: "250m"       # Initial CPU request (250 milliCPU or 0.25 CPU Core)
          envFrom:
          - configMapRef:
              name: todo
